#!/usr/bin/env python3
"""
OTAUD — Audit Report Generator
Generates HTML/JSON/TXT reports from audit log data.
Author: Ali AlEnezi (SiteQ8)
"""

import argparse
import json
import re
import os
from datetime import datetime


def parse_log(log_path):
    """Parse OTAUD log file into structured findings."""
    findings = {"critical": [], "warning": [], "info": []}
    try:
        with open(log_path, 'r') as f:
            for line in f:
                line = line.strip()
                if '[CRIT]' in line:
                    findings['critical'].append(line.split('[CRIT]')[-1].strip())
                elif '[WARN]' in line:
                    findings['warning'].append(line.split('[WARN]')[-1].strip())
                elif '[INFO]' in line:
                    findings['info'].append(line.split('[INFO]')[-1].strip())
    except FileNotFoundError:
        print(f"Log file not found: {log_path}")
    return findings


def generate_html_report(findings, target, standard, output_path):
    """Generate professional HTML audit report."""
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>OTAUD Audit Report — {target}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:'Segoe UI',system-ui,sans-serif; background:#0a0e17; color:#c8ccd4; }}
.container {{ max-width:1000px; margin:0 auto; padding:40px 20px; }}
.header {{ text-align:center; margin-bottom:40px; padding:40px; background:linear-gradient(135deg,#0d1321,#1a2332);
           border:1px solid #1e3a5f; border-radius:12px; }}
.header h1 {{ color:#f0c040; font-size:28px; letter-spacing:2px; }}
.header .meta {{ color:#7a8599; margin-top:10px; font-size:14px; }}
.summary {{ display:grid; grid-template-columns:repeat(3,1fr); gap:20px; margin:30px 0; }}
.stat {{ padding:24px; border-radius:10px; text-align:center; border:1px solid #1e3a5f; }}
.stat.critical {{ background:#2a1015; border-color:#e74c3c; }}
.stat.warning {{ background:#2a2010; border-color:#f39c12; }}
.stat.info {{ background:#0d1a2a; border-color:#3498db; }}
.stat .number {{ font-size:42px; font-weight:bold; }}
.stat.critical .number {{ color:#e74c3c; }}
.stat.warning .number {{ color:#f39c12; }}
.stat.info .number {{ color:#3498db; }}
.stat .label {{ color:#7a8599; margin-top:5px; text-transform:uppercase; font-size:12px; letter-spacing:1px; }}
.section {{ margin:30px 0; }}
.section h2 {{ color:#f0c040; font-size:18px; margin-bottom:15px; padding-bottom:8px; border-bottom:1px solid #1e3a5f; }}
.finding {{ padding:12px 16px; margin:8px 0; border-radius:8px; border-left:4px solid; font-size:14px; }}
.finding.critical {{ background:#1a0d0f; border-color:#e74c3c; }}
.finding.warning {{ background:#1a1508; border-color:#f39c12; }}
.finding.info {{ background:#0a1520; border-color:#3498db; }}
.footer {{ text-align:center; margin-top:40px; padding:20px; color:#4a5568; font-size:12px; }}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>OTAUD AUDIT REPORT</h1>
        <div class="meta">
            Target: {target} | Standard: {standard.upper()} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </div>
    <div class="summary">
        <div class="stat critical"><div class="number">{len(findings['critical'])}</div><div class="label">Critical</div></div>
        <div class="stat warning"><div class="number">{len(findings['warning'])}</div><div class="label">Warnings</div></div>
        <div class="stat info"><div class="number">{len(findings['info'])}</div><div class="label">Informational</div></div>
    </div>
"""
    if findings['critical']:
        html += '    <div class="section"><h2>Critical Findings</h2>\n'
        for f in findings['critical']:
            html += f'        <div class="finding critical">{f}</div>\n'
        html += '    </div>\n'

    if findings['warning']:
        html += '    <div class="section"><h2>Warnings</h2>\n'
        for f in findings['warning']:
            html += f'        <div class="finding warning">{f}</div>\n'
        html += '    </div>\n'

    if findings['info']:
        html += '    <div class="section"><h2>Informational</h2>\n'
        for f in findings['info'][:50]:
            html += f'        <div class="finding info">{f}</div>\n'
        html += '    </div>\n'

    html += """
    <div class="footer">
        Generated by OTAUD v1.0.0 — Ali AlEnezi (SiteQ8)<br>
        https://github.com/SiteQ8/OTAUD
    </div>
</div>
</body>
</html>"""

    with open(output_path, 'w') as f:
        f.write(html)
    print(f"[+] HTML report saved: {output_path}")


def generate_json_report(findings, target, standard, output_path):
    """Generate JSON report."""
    report = {
        "tool": "OTAUD",
        "version": "1.0.0",
        "target": target,
        "standard": standard,
        "timestamp": datetime.now().isoformat(),
        "summary": {
            "critical": len(findings['critical']),
            "warning": len(findings['warning']),
            "info": len(findings['info'])
        },
        "findings": findings
    }
    with open(output_path, 'w') as f:
        json.dump(report, f, indent=2)
    print(f"[+] JSON report saved: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="OTAUD Report Generator")
    parser.add_argument("--log", "-l", required=True, help="Path to OTAUD log file")
    parser.add_argument("--target", "-t", default="unknown", help="Target identifier")
    parser.add_argument("--format", "-f", choices=["html", "json", "txt"], default="html")
    parser.add_argument("--output", "-o", required=True, help="Output file path")
    parser.add_argument("--standard", "-s", default="iec62443")
    args = parser.parse_args()

    findings = parse_log(args.log)
    if args.format == "html":
        generate_html_report(findings, args.target, args.standard, args.output)
    elif args.format == "json":
        generate_json_report(findings, args.target, args.standard, args.output)
    else:
        print(f"[+] Text report is generated by otaud.sh directly")


if __name__ == "__main__":
    main()
